# Lista de Exercícios 10
Ianka Karúzia Rabelo de Oliveira - 365560

In [1]:
import numpy as np
import pandas as pd
from sklearn.linear_model import SGDClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [2]:
df = pd.read_csv('binary.csv')

In [3]:
df.head()

admit  gre   gpa  rank
0      0  380  3.61     3
1      1  660  3.67     3
2      1  800  4.00     1
3      1  640  3.19     4
4      0  520  2.93     4

In [4]:
print('Class labels', np.unique(df['admit']))

Class labels [0 1]


In [5]:
# Train/Test Split
X, y = df.iloc[:, 1:].values, df.iloc[:,0].values

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0, stratify=y)

In [6]:
# Standardization
std = StandardScaler()
X_train_std = std.fit_transform(X_train)
X_test_std = std.transform(X_test)

### Sem Regularização
- **Alpha: 0.0001**

In [7]:
model_none = SGDClassifier(penalty='none', alpha=0.0001, random_state=0, max_iter=5)
model_none.fit(X_train_std, y_train)
y_pred = model_none.predict(X_test_std)
print('accuracy_score:{}\nintercept_:\n{}\ncoef_:\n{}'.format(accuracy_score(y_test, y_pred), model_none.intercept_, model_none.coef_))

accuracy_score:0.6166666666666667
intercept_:
[-4.24303181]
coef_:
[[-6.47497185  6.03313697 -7.15383907]]


- **Alpha: 0.01**

In [8]:
model_none = SGDClassifier(penalty='none', alpha=0.01, random_state=0, max_iter=5)
model_none.fit(X_train_std, y_train)
y_pred = model_none.predict(X_test_std)
print('accuracy_score:{}\nintercept_:\n{}\ncoef_:\n{}'.format(accuracy_score(y_test, y_pred), model_none.intercept_, model_none.coef_))

accuracy_score:0.6833333333333333
intercept_:
[-0.98698421]
coef_:
[[ 0.0221446  0.3534601 -0.2107745]]


- **Alpha: 1**

In [9]:
model_none = SGDClassifier(penalty='none', alpha=1, random_state=0, max_iter=5)
model_none.fit(X_train_std, y_train)
y_pred = model_none.predict(X_test_std)
print('accuracy_score:{}\nintercept_:\n{}\ncoef_:\n{}'.format(accuracy_score(y_test, y_pred), model_none.intercept_, model_none.coef_))

accuracy_score:0.7333333333333333
intercept_:
[-1.34130653]
coef_:
[[ 0.34890908  0.43369854 -0.86170738]]


- **Alpha: 10**

In [10]:
model_none = SGDClassifier(penalty='none', alpha=10, random_state=0, max_iter=5)
model_none.fit(X_train_std, y_train)
y_pred = model_none.predict(X_test_std)
print('accuracy_score:{}\nintercept_:\n{}\ncoef_:\n{}'.format(accuracy_score(y_test, y_pred), model_none.intercept_, model_none.coef_))

accuracy_score:0.7416666666666667
intercept_:
[-0.75271383]
coef_:
[[ 0.66391879  0.08422368 -0.7955193 ]]


- **Alpha: 100**

In [11]:
model_none = SGDClassifier(penalty='none', alpha=100, random_state=0, max_iter=5)
model_none.fit(X_train_std, y_train)
y_pred = model_none.predict(X_test_std)
print('accuracy_score:{}\nintercept_:\n{}\ncoef_:\n{}'.format(accuracy_score(y_test, y_pred), model_none.intercept_, model_none.coef_))

accuracy_score:0.7333333333333333
intercept_:
[-0.34919719]
coef_:
[[ 0.45296725  0.01061688 -0.49585002]]


**Modelo com Alpha 10 Obteve Melhor Acurácia**

### Regularização l1
- **Alpha: 0.0001**

In [12]:
model_l1 = SGDClassifier(penalty='l1', alpha=0.0001, random_state=0, max_iter=5)
model_l1.fit(X_train_std, y_train)
y_pred = model_l1.predict(X_test_std)
print('accuracy_score:{}\nintercept_:\n{}\ncoef_:\n{}'.format(accuracy_score(y_test, y_pred), model_l1.intercept_, model_l1.coef_))

accuracy_score:0.5833333333333334
intercept_:
[0.01195232]
coef_:
[[-3.27282762  5.49421398 -8.54312128]]


- **Alpha: 0.01**

In [13]:
model_l1 = SGDClassifier(penalty='l1', alpha=0.01, random_state=0, max_iter=5)
model_l1.fit(X_train_std, y_train)
y_pred = model_l1.predict(X_test_std)
print('accuracy_score:{}\nintercept_:\n{}\ncoef_:\n{}'.format(accuracy_score(y_test, y_pred), model_l1.intercept_, model_l1.coef_))

accuracy_score:0.6833333333333333
intercept_:
[-1.07590361]
coef_:
[[ 0.          0.11067859 -0.10788836]]


- **Alpha: 1**

In [14]:
model_l1 = SGDClassifier(penalty='l1', alpha=1, random_state=0, max_iter=5)
model_l1.fit(X_train_std, y_train)
y_pred = model_l1.predict(X_test_std)
print('accuracy_score:{}\nintercept_:\n{}\ncoef_:\n{}'.format(accuracy_score(y_test, y_pred), model_l1.intercept_, model_l1.coef_))

accuracy_score:0.6833333333333333
intercept_:
[-1.00066861]
coef_:
[[0. 0. 0.]]


- **Alpha: 10**

In [15]:
model_l1 = SGDClassifier(penalty='l1', alpha=10, random_state=0, max_iter=5)
model_l1.fit(X_train_std, y_train)
y_pred = model_l1.predict(X_test_std)
print('accuracy_score:{}\nintercept_:\n{}\ncoef_:\n{}'.format(accuracy_score(y_test, y_pred), model_l1.intercept_, model_l1.coef_))

accuracy_score:0.6833333333333333
intercept_:
[-0.94868944]
coef_:
[[0. 0. 0.]]


- **Alpha: 100**

In [16]:
model_l1 = SGDClassifier(penalty='l1', alpha=100, random_state=0, max_iter=5)
model_l1.fit(X_train_std, y_train)
y_pred = model_l1.predict(X_test_std)
print('accuracy_score:{}\nintercept_:\n{}\ncoef_:\n{}'.format(accuracy_score(y_test, y_pred), model_l1.intercept_, model_l1.coef_))

accuracy_score:0.6833333333333333
intercept_:
[-0.35668417]
coef_:
[[0. 0. 0.]]


**Os modelos com alpha 0.01, 1, 10, 100 obtiveram o mesmo valor de acurácia**

### Regularização l2
- **Alpha: 0.0001**

In [17]:
model_l2 = SGDClassifier(penalty='l2', alpha=0.0001, random_state=0, max_iter=5)
model_l2.fit(X_train_std, y_train)
y_pred = model_l2.predict(X_test_std)
print('accuracy_score:{}\nintercept_:\n{}\ncoef_:\n{}'.format(accuracy_score(y_test, y_pred), model_l2.intercept_, model_l2.coef_))

accuracy_score:0.6083333333333333
intercept_:
[-0.22774255]
coef_:
[[  0.21775132   5.65669395 -10.9034331 ]]


- **Alpha: 0.01**

In [18]:
model_l2 = SGDClassifier(penalty='l2', alpha=0.01, random_state=0, max_iter=5)
model_l2.fit(X_train_std, y_train)
y_pred = model_l2.predict(X_test_std)
print('accuracy_score:{}\nintercept_:\n{}\ncoef_:\n{}'.format(accuracy_score(y_test, y_pred), model_l2.intercept_, model_l2.coef_))

accuracy_score:0.6833333333333333
intercept_:
[-0.99967146]
coef_:
[[ 0.02742837  0.38325508 -0.18283881]]


- **Alpha: 1**

In [19]:
model_l2 = SGDClassifier(penalty='l2', alpha=1, random_state=0, max_iter=5)
model_l2.fit(X_train_std, y_train)
y_pred = model_l2.predict(X_test_std)
print('accuracy_score:{}\nintercept_:\n{}\ncoef_:\n{}'.format(accuracy_score(y_test, y_pred), model_l2.intercept_, model_l2.coef_))

accuracy_score:0.6833333333333333
intercept_:
[-0.99980314]
coef_:
[[ 0.00092415  0.00360407 -0.00198001]]


- **Alpha: 10**

In [20]:
model_l2 = SGDClassifier(penalty='l2', alpha=10, random_state=0, max_iter=5)
model_l2.fit(X_train_std, y_train)
y_pred = model_l2.predict(X_test_std)
print('accuracy_score:{}\nintercept_:\n{}\ncoef_:\n{}'.format(accuracy_score(y_test, y_pred), model_l2.intercept_, model_l2.coef_))

accuracy_score:0.6833333333333333
intercept_:
[-0.9470707]
coef_:
[[ 0.01097984  0.01771609 -0.01665724]]


- **Alpha: 100**

In [21]:
model_l2 = SGDClassifier(penalty='l2', alpha=100, random_state=0, max_iter=5)
model_l2.fit(X_train_std, y_train)
y_pred = model_l2.predict(X_test_std)
print('accuracy_score:{}\nintercept_:\n{}\ncoef_:\n{}'.format(accuracy_score(y_test, y_pred), model_l2.intercept_, model_l2.coef_))

accuracy_score:0.6833333333333333
intercept_:
[-0.35668417]
coef_:
[[ 0.00131703  0.00198347 -0.001821  ]]


**Os modelos com alpha 0.01, 1, 10, 100 obtiveram o mesmo valor de acurácia**

### Regularização Elastic Net
- **Alpha: 0.0001**

In [22]:
model_en = SGDClassifier(penalty='elasticnet', alpha=0.0001, random_state=0, max_iter=5)
model_en.fit(X_train_std, y_train)
y_pred = model_en.predict(X_test_std)
print('accuracy_score:{}\nintercept_:\n{}\ncoef_:\n{}'.format(accuracy_score(y_test, y_pred), model_en.intercept_, model_en.coef_))

accuracy_score:0.6083333333333333
intercept_:
[-0.389888]
coef_:
[[ -0.20136738   5.25308175 -11.21983356]]


- **Alpha: 0.01**

In [23]:
model_en = SGDClassifier(penalty='elasticnet', alpha=0.01, random_state=0, max_iter=5)
model_en.fit(X_train_std, y_train)
y_pred = model_en.predict(X_test_std)
print('accuracy_score:{}\nintercept_:\n{}\ncoef_:\n{}'.format(accuracy_score(y_test, y_pred), model_en.intercept_, model_en.coef_))

accuracy_score:0.6833333333333333
intercept_:
[-1.03709143]
coef_:
[[ 0.          0.15503843 -0.14340616]]


- **Alpha: 1**

In [24]:
model_en = SGDClassifier(penalty='elasticnet', alpha=1, random_state=0, max_iter=5)
model_en.fit(X_train_std, y_train)
y_pred = model_en.predict(X_test_std)
print('accuracy_score:{}\nintercept_:\n{}\ncoef_:\n{}'.format(accuracy_score(y_test, y_pred), model_en.intercept_, model_en.coef_))

accuracy_score:0.6833333333333333
intercept_:
[-1.00046583]
coef_:
[[0. 0. 0.]]


- **Alpha: 10**

In [25]:
model_en = SGDClassifier(penalty='elasticnet', alpha=10, random_state=0, max_iter=5)
model_en.fit(X_train_std, y_train)
y_pred = model_en.predict(X_test_std)
print('accuracy_score:{}\nintercept_:\n{}\ncoef_:\n{}'.format(accuracy_score(y_test, y_pred), model_en.intercept_, model_en.coef_))

accuracy_score:0.6833333333333333
intercept_:
[-0.94868944]
coef_:
[[0. 0. 0.]]


- **Alpha: 100**

In [26]:
model_en = SGDClassifier(penalty='elasticnet', alpha=100, random_state=0, max_iter=5)
model_en.fit(X_train_std, y_train)
y_pred = model_en.predict(X_test_std)
print('accuracy_score:{}\nintercept_:\n{}\ncoef_:\n{}'.format(accuracy_score(y_test, y_pred), model_en.intercept_, model_en.coef_))

accuracy_score:0.6833333333333333
intercept_:
[-0.35668417]
coef_:
[[0. 0. 0.]]


**Os modelos com alpha 0.01, 1, 10, 100 obtiveram o mesmo valor de acurácia**