# Lista de Exercícios 3
- Ianka Karúzia Rabelo de Oliveira - 365560

In [5]:
from libs import metrics, stats, resample
import numpy as np
from sklearn import linear_model, datasets
from sklearn.preprocessing import StandardScaler

In [6]:
X = np.array([[1400], [1600], [1700], [1875], [1100], [1550], [2350], [2450], [1425], [1700]])
y = np.array([245000, 312000, 279000, 308000, 199000, 219000, 405000, 324000, 319000, 255000])
#X, y = datasets.load_boston(return_X_y=True)

In [7]:
# Média
stats.mean(X)

1715.0

In [8]:
# Desvio Padrão
stats.stdev(X)

array([ 396.42149286])

In [9]:
# Variância
stats.var(X)

array([ 157150.])

In [10]:
# Separando o Dataset em Train e Test 
n_elem = len(X)
idx_train, idx_test = resample.split_train_test(n_elem, 0.7, 0)

In [11]:
std_scale = StandardScaler().fit(X[idx_train])
X_train_std = std_scale.transform(X[idx_train])
X_test_std = std_scale.transform(X[idx_test])

C:\Program Files\Anaconda3\lib\site-packages\sklearn\utils\validation.py:429: DataConversionWarning: Data with input dtype int32 was converted to float64 by StandardScaler.
  warnings.warn(msg, _DataConversionWarning)


In [12]:
idx_train

[2, 8, 4, 9, 1, 6, 7]

In [13]:
idx_test

[3, 0, 5]

In [14]:
X_train = X[idx_train]
X_train

array([[1700],
       [1425],
       [1100],
       [1700],
       [1600],
       [2350],
       [2450]])

In [15]:
y_train = y[idx_train]
y_train

array([279000, 319000, 199000, 255000, 312000, 405000, 324000])

In [16]:
X_test = X[idx_test]
X_test

array([[1875],
       [1400],
       [1550]])

In [17]:
y_test = y[idx_test]
y_test

array([308000, 245000, 219000])

In [18]:
#Criando os modelos
modelSK = linear_model.LinearRegression()

In [19]:
modelSK.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [20]:
y_pred = modelSK.predict(X_test)

In [21]:
y_pred

array([ 310458.49752129,  262834.11719842,  277873.39519512])

In [22]:
# MSE
metrics.mse(y_test, y_pred)

1263392202.7033181

In [23]:
# RMSE
metrics.rmse(y_test, y_pred)

35544.228824146936

In [24]:
# MAE
metrics.mae(y_test, y_pred)

26388.669971611369

In [25]:
#Xt = np.reshape(Xtreino,[Xtreino.shape[0], 1])

In [29]:
import libs.linear_model as lr

In [30]:
modelLR = lr.SimpleLinearRegression()

In [31]:
Xt = np.reshape(X_train,[X_train.shape[0], 1])

In [32]:
Xt

array([[1700],
       [1425],
       [1100],
       [1700],
       [1600],
       [2350],
       [2450]])

In [33]:
modelLR.fit(Xt, y_train)

In [34]:
Xtest = np.reshape(X_test,[X_test.shape[0], 1])

In [35]:
y_predLR = modelLR.predict(Xtest)

In [36]:
y_predLR

array([ 310458.49752129,  262834.11719842,  277873.39519512])

In [37]:
metrics.mse(y_test, y_predLR)

1263392202.7033188

In [38]:
metrics.rmse(y_test, y_predLR)

35544.228824146951

In [39]:
metrics.mae(y_test, y_predLR)

26388.669971611391